### PR TITLE
Removed requirement to be registered to go to About page.

### PR DESCRIPTION
**Pull request by btamayo**
Just removed the 'isRegistered()' check before going to about.

This is for #3, in case you would like this feature.

### CODE REVIEW

**Comment by rkrishnasanka** [comment]
I think you should comment on #3 itself. That way the issue can be closed. Now there are two issues regarding this. @btamayo

**Comment by btamayo** [comment]
@rkrishnasanka I did comment there as well :)

**Comment by rkrishnasanka** [comment]
Cool 😄 I was just saying so as to avoid duplication.

**Comment by PrashantVaidyanathan** [comment]
Thanks. Incorporated in commit: 27f6354f41cd2997610e79e2a41ded61f2c3fa91

**Pull request closed without merging**
